services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: food
      POSTGRES_USER: food
      POSTGRES_PASSWORD: food
    ports:
      - "5433:5432"   # или уберите ports вовсе, если не нужен доступ с хоста
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U food -d food"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth:
    build:
      context: ..
      dockerfile: deploy/auth.Dockerfile
    environment:
      APP_ENV: dev
      HTTP_PORT: "8080"
      DATABASE_URL: "postgres://food:food@postgres:5432/food?sslmode=disable"
      JWT_SECRET: "change_me_in_real_env"
      ACCESS_TTL: "15m"
      REFRESH_TTL: "720h"
      BCRYPT_COST: "12"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  migrate:
    profiles: ["tools"]
    image: migrate/migrate:4
    volumes:
      - ../migrations:/migrations:ro
    entrypoint: ["migrate"]
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  pgdata:
