services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: food
      POSTGRES_USER: food
      POSTGRES_PASSWORD: food
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U food -d food"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth:
    build:
      context: ..
      dockerfile: deploy/auth.Dockerfile
    environment:
      APP_ENV: dev
      HTTP_PORT: "8080"
      DATABASE_URL: "postgres://food:food@postgres:5432/food?sslmode=disable"
      JWT_SECRET: "change_me_in_real_env"
      ACCESS_TTL: "15m"
      REFRESH_TTL: "720h" # 30 дней
      BCRYPT_COST: "12"
    ports:
      - "18080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
